theme: minima
title: deva.cloud
author:
  name: Quinn Michaels
  email: "quinn@indra.ai"
description: deva.cloud is the core multi-agent system for the Indra Quantum Computing Environment.

social_links:
  twitter: quinnmichaels
  github: quinnmichaels
  instagram: quinnmichaels
  youtube: quinnmichaels

plugins:
 - jekyll-feed
 - jekyll-seo-tag

minima:
  date_format: "%b %-d, %Y"
